### ISSUE TITLE
Reunión Jueves 12/10/17

### ISSUE THREAD

**Issue by anapareciendo** [InnosoftDaysPresidencia/Programa#1]
El objetivo de esta reunión es decidir el tema de las jornadas y coordinarnos entre los grupos de mañana y tarde. Además de dejar constancia de la información necesaria a aportar a las personas con las que se contacten (web, facebook, twitter, etc).

Se realizará via skype a las 12:00 AM.

**Comment by anapareciendo** [comment]
Se ha realizado un guión entre los coordinadores de ambos grupos con el objetivo de llevar un orden de los temas a tratar durante la reunión.

**Comment by YamiJosema** [comment]
[Acta_1210.pdf](https://github.com/InnosoftDaysPresidencia/Programa/blob/master/Actas/Acta_1210.pdf)
